# Generated by Django 3.1 on 2021-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.ImageField(blank=True, help_text='Send a file or image ', upload_to='msgpics'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Please upload your photo', upload_to='profile_pics'),
        ),
    ]
