# Generated by Django 3.1 on 2021-11-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20211117_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('*****', '*****'), ('****', '****'), ('***', '***'), ('**', '**'), ('*', '*')], default='*****', max_length=255),
        ),
    ]
