# Generated by Django 3.1 on 2021-11-18 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_auto_20211118_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader_writer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 18, 10, 34, 45, 144464, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
