# Generated by Django 3.1 on 2021-11-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_reader_writer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader_writer',
            name='writer',
        ),
    ]
