# Generated by Django 3.1 on 2021-11-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_auto_20211118_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[(5, '*****'), (4, '****'), (3, '***'), (2, '**'), (1, '*')], default='*****', max_length=255),
        ),
    ]
