# Generated by Django 3.1 on 2021-11-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_auto_20211118_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default='*****', max_length=255),
        ),
    ]
